In [1]:
import pandas as pd

In [3]:
data = pd.read_pickle('../data/raw/hurb_term.pkl')

In [22]:
data[(data.language == 'pt') &
     (~data.username.str.contains('hurb'))]#.tweet

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1529487156607172611,1528913078821310470,1.653493e+12,2022-05-25 15:38:49,+0000,,@anacarolbitt @annajuliasqr @nsrrdpcbr @fernan...,pt,[],[],...,,,,,,"[{'screen_name': 'anacarolbitt', 'name': 'Ana ...",,,,
1,1529486419059789828,1529260345201766401,1.653493e+12,2022-05-25 15:35:53,+0000,,"@zxdebn @yarasenger Oi Kiara, como vai? Não pr...",pt,[],[],...,,,,,,"[{'screen_name': 'zxdebn', 'name': 'Kirara', '...",,,,
2,1529484734589505538,1529241358757777413,1.653493e+12,2022-05-25 15:29:11,+0000,,@HurbBrasil @JulianaGloria6 Hurb me contrata,pt,[],[],...,,,,,,"[{'screen_name': 'HurbBrasil', 'name': 'Hurb',...",,,,
3,1529483526852444165,1529260345201766401,1.653492e+12,2022-05-25 15:24:23,+0000,,"@yarasenger Oie, Yara! Sentimos muito, essa re...",pt,[],[],...,,,,,,"[{'screen_name': 'yarasenger', 'name': 'Yara M...",,,,
12,1529468122603864071,1529468122603864071,1.653489e+12,2022-05-25 14:23:11,+0000,,E eu que no auge do vinho comprei um pacote de...,pt,[],[],...,,,,,,[],,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,1526528079291629574,1526355930119606277,1.652788e+12,2022-05-17 11:40:30,+0000,,@lisleymonteiroo tô quase fechando uma no hurb...,pt,[],[],...,,,,,,"[{'screen_name': 'lisleymonteiroo', 'name': 'l...",,,,
832,1526520392604606464,1526404976750247937,1.652786e+12,2022-05-17 11:09:57,+0000,,@eniacarvalho eu vou viajar pela hurb mes que ...,pt,[],[],...,,,,,,"[{'screen_name': 'eniacarvalho', 'name': 'odei...",,,,
833,1526494776228552704,1526343354367324160,1.652780e+12,2022-05-17 09:28:10,+0000,,"@StarlingDebora @juliette Debora, não tenha dú...",pt,[],[],...,,,,,,"[{'screen_name': 'StarlingDebora', 'name': 'De...",,,,
834,1526494548704337920,1526471776842272770,1.652780e+12,2022-05-17 09:27:15,+0000,,"@_dadivadeisis Isis, pensamento positivo que v...",pt,[],[],...,,,,,,"[{'screen_name': '_dadivadeisis', 'name': 'zad...",,,,
838,1526449813352497154,1526449813352497154,1.652769e+12,2022-05-17 06:29:30,+0000,,Riscos de estar acordado esta hora da madrugad...,pt,[],[],...,,,,,,[],,,,